pipeline {
  agent any

  parameters {
    string(defaultValue: '', description: 'persons name', name: 'name')
  }

  stages {
    stage('test') {
      steps {
        script {
          sh 'echo "Hello World!"'
        }
      }
    }
    stage('stage2') {
      steps {
        script {
          sh 'echo "this is the second stage"'
        }
      }
    }
  }
  post {
    cleanup {
      cleanWs()
    }
  }
}
